name: auto-update-build-number

on:
  workflow_dispatch:

jobs:
  update-build-number:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: set homebrew path
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: set up fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm
          fvm install
        
      - name: bump build jumber
        run: |
          dart pub global activate cider
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cider bump build --bump-build
          fvm flutter pub get

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: bump up
          title: Bump up version code
          labels: bump up


