name: create-tag-and-release

on:
  push:
    branches:
      - main
      - test

jobs:
  update-build-number:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: echo event info
        run: |
          echo github.event.label
          echo github.event.pull_request.labels


