name: test-push-tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag name'
        required: true
        type: string

jobs:
  test-push-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: create tag & release
        run: |
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
